src/App.css
src/App.jsx
src/components/poetry.jsx

CO-authored-by: ANNA <anna.maynard@gmail.com>
CO-authoredby: TEDDY <teddythibodeau@gmail.com>

POETRY -> themes,categories,sentiment,emotion, GENERATE

---

src/components/poetry.jsx

hardcoded select values, post working, still getting a 400 error on the post

Post Works 90%

---

node_modules/.vite/deps/_metadata.json
src/App.jsx
src/components/poetry.jsx
src/components/response.jsx

Output and setOutput work correctly in response.jsx

Poetry post 4

---

prompt.json
promptresponse.jsx
src/App.jsx
src/components/landing.jsx
src/components/mediums/creativewriting.jsx
src/components/mediums/movement.jsx
src/components/mediums/music.jsx
src/components/mediums/visualart.jsx
src/components/promtresponse/creativewrtitingpromt.jsx
src/components/promtresponse/movementprompt.jsx
src/components/promtresponse/musicprompt.jsx
src/components/promtresponse/visualartprompt.jsx
unsuedcomponents/template.jsx

Co-Authored by : Anna Maynard <anna.maynard@gmail.com>
2 bugs - 
import / routes 
selected theme in movement not working 
movement POST not working 
routing not working

Co-Authored by : Theodore Thibodeau <teddythibodeau@gmail.com>

---

prompt.json
src/App.jsx
src/components/mediums/movement.jsx

Co-Authored by : Theodore Thibodeau <teddythibodeau@gmail.com>
Co-Authored by : Anna Maynard <anna.maynard@gmail.com>

FIXED BUGGS YAYAYAY, router and promptpost

---

node_modules/.vite/deps/_metadata.json
src/App.jsx
src/components/landing.jsx

very few changes to app.jsx and routes

Routing Changes

---

src/components/mediums/creativewriting.jsx
src/components/mediums/movement.jsx
src/components/mediums/music.jsx
src/components/mediums/visualart.jsx

components 3

---

node_modules/.vite/deps/_metadata.json
src/components/mediums/creativewriting.jsx
src/components/mediums/movement.jsx
src/components/mediums/music.jsx
src/components/mediums/visualart.jsx
src/components/navbar.jsx

Co-Authored by : Anna Maynard <anna.maynard@gmail.com>
All major components work, every POST and GET request to chatgpt works

Components-4 (aka the big one)

---

prompt.json
src/App.css
src/App.jsx
src/components/landing.jsx
src/components/mediums/music.jsx

Components 4 part 2

---

src/App.css
src/App.jsx
src/components/mediums/creativewriting.jsx
src/components/mediums/movement.jsx
src/components/mediums/music.jsx
src/components/mediums/visualart.jsx
src/components/promptparents/movementpromptshare.jsx
src/components/promptparents/musicpromptshare.jsx
src/components/promptparents/visualartpromptshare.jsx
src/components/promptresponse/movementprompt.jsx
src/components/promptresponse/musicprompt.jsx
src/components/promptresponse/visualartprompt.jsx
src/index.css
src/tailwind.config.js

finished the 4 main components and now the prompt shows up in 2 places

Tailwind-1

---

index.html
node_modules/.vite/deps/_metadata.json
src/App.jsx
src/components/mediums/creativewriting.jsx
src/components/navbar.jsx
src/index.css
tailwind.config.js
unsuedcomponents/tailwind.config.js

Co-Authored by : Anna Maynard <anna.maynard@gmail.com> tailwind css

Tailwind-3

---

src/components/mediums/creativewriting.jsx
src/index.css

Dictionary-1

---

node_modules/.vite/deps/_metadata.json
src/App.jsx
src/components/landing.jsx
src/components/mediums/creativewriting.jsx
src/components/parameters/mediumsCW.jsx
src/components/parameters/themesCW.jsx

began the process of making components for each of the json files

Dictionary-3

---

prompt.json
src/components/landing.jsx
src/components/mediums/creativewriting.jsx
src/components/mediums/music.jsx
src/components/parameters/ParameterComponent.jsx

Changes to be committed:
(use "git reset HEAD <file>..." to unstage)
modified:   prompt.json
modified:   src/components/landing.jsx
modified:   src/components/mediums/creativewriting.jsx
modified:   src/components/mediums/music.jsx
new file:   src/components/parameters/ParameterComponent.jsx

parameter component

---

src/components/footer.jsx
src/components/landing.jsx
src/components/mediums/creativewriting.jsx
src/components/parameters/MediumNav.jsx
src/components/parameters/ParameterComponent.jsx

footer and writing style

---

prompt.json
src/components/create/dictionary.jsx
src/components/folio.jsx
src/components/mediums/movement.jsx
src/components/mediums/music.jsx

Improvements 1

---

prompt.json
src/components/mediums/creativewriting.jsx
src/components/mediums/movement.jsx
src/components/mediums/music.jsx
src/components/mediums/visualart.jsx
src/components/promptresponse/visualartprompt.jsx

generate button appears in its own state

improvements-2

---

src/components/mediums/creativewriting.jsx
src/components/mediums/movement.jsx
src/components/mediums/music.jsx
src/components/mediums/visualart.jsx
src/components/promptresponse/visualartprompt.jsx

begin button appears AFTER generate button is selected

improvements-3

---

src/components/footer.jsx
src/components/mediums/creativewriting.jsx

small changes, working on back and forward buttons

Improvements 4

---

src/components/create/dictionary.jsx

dropdown menu complete in dictionary

improvements-6

---

src/components/footer.jsx
src/components/mediums/creativewriting.jsx
src/components/mediums/movement.jsx
src/components/mediums/music.jsx
src/components/mediums/visualart.jsx
src/components/parameters/ParameterComponent.jsx

Improvements 7

---

src/components/create/dictionary.jsx
src/components/mediums/creativewriting.jsx
src/components/mediums/movement.jsx
src/components/mediums/music.jsx
src/components/mediums/visualart.jsx
src/components/parameters/MediumNav.jsx
src/components/robotdict.jsx

Improvements 8
